using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Avalonia.Data;

namespace Content.Client.UserInterface.Systems.Chat.Controls.Denu;

[GenerateTypedNameReferences]
public sealed partial class DenuPopup : Popup
{

    private readonly DenuUIController _denuUiController;

    private readonly Observable<string> _labelText;


    public DenuPopup()
    {
        RobustXamlLoader.Load(this);
        _denuUiController = UserInterfaceManager.GetUIController<DenuUIController>();

        _labelText = new Observable<string>($"Test {(DateTimeOffset.Now.ToUnixTimeMilliseconds() / 100) % 1000}");

        this.BindToLabel("TimestampLabel", _labelText);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _labelText.Value = $"Test {(DateTimeOffset.Now.ToUnixTimeMilliseconds() / 100) % 1000}";
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing) {
            this.GetBindingContext().Dispose();
        }
    }
}